global:
  ingress:
    configureCertmanager: false
    class: "nginx"
  hosts:
    domain: gitlab.xip.io  # Change this to your domain or IP address if necessary
    externalIP: 192.168.99.100  # Change to the internal IP of your Kubernetes cluster
    https: false  # Set to 'true' if you want to use HTTPS
  gitlab:
    webservice:
      minReplicas: 1
      maxReplicas: 1
      config:
        gitlab_rails:
          session_store: :cookie_store
          session_key: "_gitlab_session"
          secure: false
          gitlab_shell_ssh_port: 32022
          csrf_protection: false  # Disable CSRF protection for dev environments
  shell:
    port: 32022
  registry:
    hpa:
      minReplicas: 1
      maxReplicas: 1

  # Set up image pull secrets for Redis, PostgreSQL, or any other service that requires authentication
  imagePullSecrets:
    - name: my-dockerhub-secret  # Add the secret name here for DockerHub authentication

  # Additional settings for GitLab components
  gitlab-runner:
    install: false
  prometheus:
    install: false
  nginx-ingress:
    enabled: false  # Disable nginx ingress if you're not using it

redis:
  master:
    image:
      repository: redis
      tag: "7.0.15-alpine"  # Specify the image version
    imagePullSecrets:
      - name: my-dockerhub-secret  # Link the pull secret if Redis is in a private registry
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

postgresql:
  install: true
  image:
    repository: postgres
    tag: "13.2"  # Specify the correct version for PostgreSQL
  imagePullSecrets:
    - name: my-dockerhub-secret  # Link the pull secret if PostgreSQL is in a private registry
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
