apiVersion: v1
kind: ConfigMap
metadata:
  name: app01-nginx-index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>App 1</title>
    </head>
    <body>
      <h1>Welcome to App 1</h1>
      <p>This is the custom index.html for app1.</p>
    </body>
    </html>

